### ISSUE TITLE
Meteor is fundamentally broken

### ISSUE THREAD

**Issue by jsumners** [charlieman/ice-lotto-meteor#19]
https://github.com/meteor/meteor/issues/5124

Security updates for the version of Node that this application is running on end this October 1 (2016-10-01) -- https://github.com/nodejs/LTS#lts_schedule

If they get it fixed by that time then fine. But if not, there needs to be some _very_ serious consideration given to what needs to be done to move this to a platform that isn't so bound by non-native code.

I'll try to devote some time to that endeavor in the coming months.

**Comment by charlieman** [comment]
According to [this post](https://forums.meteor.com/t/meteor-nodejs-0-12/2769/25) Meteor 1.4 will use Node 4. I'll try the beta once it's out so we can migrate it when it gets released.

Here's the Meteor 1.4 release milestone: https://github.com/meteor/meteor/milestones/Release%201.4
And here's the pull request for the upgrade to Node 4: https://github.com/meteor/meteor/pull/6921

I guess we can also look into moving away from Meteor. I'd like at least to be able to move away from MongoDB. Also if we change the templates from Meteor's own template system and move it to React we could at least reuse that part with any other backend. This is something I wanted to try anyway so that's one more reason to do it.

**Comment by jsumners** [comment]
That's good. But my opinion remains the same -- if it can't track the platform it runs on then it is broken.

Personally, I use [Marko](http://markojs.com) for templating, [Hapi](http://hapijs.com) for a framework, and [Objection](https://www.npmjs.com/package/objection) if I want some sort of ORM-like tool.

But I have to say, Mongoose + MongoDB is a rather speedy combination. I was able to dramatically reduce response times in an application with it -- https://github.com/jscas/cas-server-mongo-repositories

**Comment by mitar** [comment]
Meteor 1.4 runs on node.js 4 (LTS).
